/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "Vibrato.h"


//==============================================================================
/**
*/
class GainAudioProcessorEditor  : public AudioProcessorEditor,
								  private Slider::Listener,
                                  public Button::Listener,
                                  public Timer::Timer
{
public:
    GainAudioProcessorEditor (GainAudioProcessor&);
    ~GainAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    
    void buttonClicked (Button* button) override ;
    void sliderValueChanged(Slider* slider) override;
    void timerCallback() override;
    
    
	void initializeSlider(Slider &slider, float minValue, float maxValue, float step, int x, int y, int width, int height, const String & suffix);
    void initializeLabel(Slider &slider, Label &label, const String & name);
    void initializeLabel(Button &button, Label &label, const String & name);
    void initializeLabel(Label &label, const String & name, int x, int y);
    void initializeToggleButton(ToggleButton &toggle, int x, int y);
    
    
    Slider          m_sliderModulationAmplitude;
    Slider          m_sliderModulationFrequency;
    Label           m_labelModulationAmplitude;
    Label           m_labelModulationFrequency;
    Label           m_labelBypass;
    Label           m_labelTitle;
    ToggleButton    m_toggleBypass;
    



private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    GainAudioProcessor& processor;


    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (GainAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
