/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "../inc/PluginProcessor.h"
#include "../inc/PluginEditor.h"
#define MIN_MOD_FREQ 0.0
#define MAX_MOD_FREQ 40.0
#define DEFAULT_MOD_FREQ 3.0

#define MIN_MOD_AMP 0.0
#define MAX_MOD_AMP 1.0
#define DEFAULT_MOD_AMP 0.1


//==============================================================================
GainAudioProcessor::GainAudioProcessor()
{
	m_bIsBypassed = false;
	m_cVibrato = 0;
	m_audioParaModulationAmplitude= new AudioParameterFloat("Mod Freq", "Modulation Frequency", MIN_MOD_FREQ, MAX_MOD_FREQ, DEFAULT_MOD_FREQ);
	m_audioParaModulationFrequency= new AudioParameterFloat("Mod Freq", "Modulation Frequency", MIN_MOD_AMP, MAX_MOD_AMP, DEFAULT_MOD_AMP);
	addParameter(m_audioParaModulationAmplitude);
	addParameter(m_audioParaModulationFrequency);

}

GainAudioProcessor::~GainAudioProcessor()
{
	CVibrato::destroyInstance(m_cVibrato);
}

//==============================================================================
const String GainAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

bool GainAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool GainAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool GainAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double GainAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int GainAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int GainAudioProcessor::getCurrentProgram()
{
    return 0;
}

void GainAudioProcessor::setCurrentProgram (int index)
{
}

const String GainAudioProcessor::getProgramName (int index)
{
    return String();
}

void GainAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void GainAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
	m_iNumChannels = std::max(getTotalNumInputChannels(), getTotalNumOutputChannels());
	m_errorCheck = CVibrato::createInstance(m_cVibrato);
	m_errorCheck = m_cVibrato->initInstance(MAX_MOD_AMP, sampleRate, m_iNumChannels);//may cause crash
	setParameter(0, getParameterDefaultValue(0));
	setParameter(1, getParameterDefaultValue(1));


}

void GainAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void GainAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    // I've added this to avoid people getting screaming feedback
    // when they first compile the plugin, but obviously you don't need to
    // this code if your algorithm already fills all the output channels.
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
        buffer.clear (i, 0, buffer.getNumSamples());

    // This is the place where you'd normally do the guts of your plugin's
    // audio processing...
    for (int channel = 0; channel < getNumInputChannels(); ++channel)
    {
        float* channelData = buffer.getWritePointer (channel);

        // ..do something to the data....
			for (int sampleIndex = 0;sampleIndex < buffer.getNumSamples();sampleIndex++)
			{
				channelData[sampleIndex] *= m_fVolume;
			}
    }
}

//==============================================================================
bool GainAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* GainAudioProcessor::createEditor()
{
    return new GainAudioProcessorEditor (*this);
}

//==============================================================================
void GainAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void GainAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new GainAudioProcessor();
}
