/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "../inc/PluginProcessor.h"
#include "../inc/PluginEditor.h"
#define MIN_MOD_FREQ 0.0
#define MAX_MOD_FREQ 10.0
#define DEFAULT_MOD_FREQ 3.0

#define MIN_MOD_AMP 0.0
#define MAX_MOD_AMP 1.0
#define DEFAULT_MOD_AMP 0.01


//==============================================================================
GainAudioProcessor::GainAudioProcessor()
{
	m_bIsBypassed = false;
	m_cVibrato = 0;
	m_audioParaModulationAmplitude= new AudioParameterFloat("Mod Freq", "Modulation Frequency", MIN_MOD_FREQ, MAX_MOD_FREQ, DEFAULT_MOD_FREQ);
	m_audioParaModulationFrequency= new AudioParameterFloat("Mod Freq", "Modulation Frequency", MIN_MOD_AMP, MAX_MOD_AMP, DEFAULT_MOD_AMP);
	addParameter(m_audioParaModulationAmplitude);
	addParameter(m_audioParaModulationFrequency);

}

GainAudioProcessor::~GainAudioProcessor()
{
	CVibrato::destroyInstance(m_cVibrato);
}

//==============================================================================
const String GainAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

bool GainAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool GainAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool GainAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double GainAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int GainAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int GainAudioProcessor::getCurrentProgram()
{
    return 0;
}

void GainAudioProcessor::setCurrentProgram (int index)
{
}

const String GainAudioProcessor::getProgramName (int index)
{
    return String();
}

void GainAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void GainAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
	m_iNumChannels = std::max(getTotalNumInputChannels(), getTotalNumOutputChannels());
	m_errorCheck = CVibrato::createInstance(m_cVibrato);
	m_errorCheck = m_cVibrato->initInstance(MAX_MOD_AMP, sampleRate, m_iNumChannels);//may cause crash
	m_cVibrato->setParam(CVibrato::VibratoParam_t::kParamModWidthInS, 0.01);
	m_cVibrato->setParam(CVibrato::VibratoParam_t::kParamModFreqInHz, 8.0);

	setParameter(0, getParameterDefaultValue(0));
	setParameter(1, getParameterDefaultValue(1));
}

void GainAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void GainAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
	if (m_bIsBypassed)
	{
		processBlockBypassed(buffer, midiMessages);
		return;
	}
	else
	{
		float** m_ppWritePointer = buffer.getArrayOfWritePointers();
		m_cVibrato->process(m_ppWritePointer, m_ppWritePointer, buffer.getNumSamples());
	}
}

//==============================================================================
bool GainAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* GainAudioProcessor::createEditor()
{
    return new GainAudioProcessorEditor (*this);
}

//==============================================================================
void GainAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void GainAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new GainAudioProcessor();
}
void GainAudioProcessor::setParam(int parameterIndex)
{

		switch (parameterIndex)
		{
		case 0:
			m_cVibrato->setParam(CVibrato::VibratoParam_t::kParamModWidthInS, m_fValueModulationAmplitude);
			break;
		case 1:
			m_cVibrato->setParam(CVibrato::VibratoParam_t::kParamModFreqInHz, m_fValueModulationFrequency);
			break;
		default:
			break;
		}

}